# Generated by Django 6.0.2 on 2026-03-20 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_firstname_user_gender_user_lastname_user_mobile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro'), ('elite', 'Elite')], default='free', max_length=10),
        ),
    ]
