# Generated by Django 6.0.2 on 2026-03-18 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_name', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('singer', 'Singer'), ('dancer', 'Dancer'), ('musician', 'Musician'), ('artist', 'Visual Artist'), ('athlete', 'Athlete'), ('coach', 'Coach'), ('other', 'Other')], default='other', max_length=20)),
                ('bio', models.TextField(blank=True)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('cover_image_url', models.URLField(blank=True)),
                ('profile_image_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gem_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OpenCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('budget', models.CharField(max_length=50)),
                ('category', models.CharField(choices=[('singer', 'Singer'), ('dancer', 'Dancer'), ('musician', 'Musician'), ('artist', 'Visual Artist'), ('athlete', 'Athlete'), ('coach', 'Coach'), ('other', 'Other')], default='other', max_length=20)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closing', 'Closing Soon'), ('closed', 'Closed')], default='open', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('posted_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_calls', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('open_call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='gems.opencall')),
            ],
            options={
                'unique_together': {('open_call', 'applicant')},
            },
        ),
    ]
